### ISSUE TITLE
Aumentar o tamanho das cartelas

### ISSUE THREAD

**Issue by jjeanjacques10** [gspetillo/bingo-online#3]
Para o público alvo acredito que o tamanho das tabelas tenha que ser maior.

![image](https://user-images.githubusercontent.com/32225403/175598282-857ce73c-750b-42d4-a259-4379a45f3b15.png)

Caso contrário pode dificultar a visualização em dia de jogos

**Comment by gspetillo** [comment]
Qual tamanho seria ideal?
Poderia enviar uma implementação para avaliarmos?
Obrigado

**Comment by jjeanjacques10** [comment]
Merge Request com sugestão de mudança

https://github.com/gspetillo/bingo-online/pull/5
